# Database configuration for different environments
# Supports PostgreSQL, MySQL, and SQLite

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000
  retry_attempts: 3
  retry_delay: 1000
  
  # Connection settings
  connect_timeout: 30
  read_timeout: 60
  write_timeout: 60
  
  # SSL configuration
  ssl_mode: prefer
  ssl_cert: /path/to/client-cert.pem
  ssl_key: /path/to/client-key.pem
  ssl_ca: /path/to/ca-cert.pem
  
  # Performance tuning
  prepared_statements: true
  statement_cache_size: 1000
  max_connections: 100
  min_connections: 10
  connection_lifetime: 3600

development:
  <<: *default
  database: ecommerce_development
  username: developer
  password: dev_password
  host: localhost
  port: 5432
  
  # Development-specific settings
  log_level: debug
  log_queries: true
  auto_vacuum: true
  
  # Test data seeding
  seed_data: true
  sample_users: 1000
  sample_products: 5000
  sample_orders: 10000

test:
  <<: *default
  database: ecommerce_test_<%= ENV['TEST_WORKER_ID'] || '1' %>
  username: test_user
  password: test_password
  host: localhost
  port: 5432
  
  # Test-specific settings
  log_level: warn
  log_queries: false
  pool: 5
  timeout: 1000
  
  # Clean slate for each test
  auto_migrate: true
  auto_seed: false
  truncate_tables: true

staging:
  <<: *default
  database: ecommerce_staging
  username: <%= ENV['STAGING_DB_USERNAME'] %>
  password: <%= ENV['STAGING_DB_PASSWORD'] %>
  host: <%= ENV['STAGING_DB_HOST'] %>
  port: <%= ENV['STAGING_DB_PORT'] || 5432 %>
  
  # Staging-specific settings
  log_level: info
  log_queries: false
  ssl_mode: require
  
  # Monitoring and metrics
  enable_metrics: true
  slow_query_threshold: 2000
  connection_pool_monitoring: true

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB_NAME'] %>
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
  port: <%= ENV['PRODUCTION_DB_PORT'] || 5432 %>
  
  # Production-specific settings
  log_level: error
  log_queries: false
  ssl_mode: require
  pool: 50
  timeout: 10000
  
  # High availability
  read_replicas:
    - host: <%= ENV['PRODUCTION_DB_READ_REPLICA_1'] %>
      port: <%= ENV['PRODUCTION_DB_READ_REPLICA_1_PORT'] || 5432 %>
      weight: 50
    - host: <%= ENV['PRODUCTION_DB_READ_REPLICA_2'] %>
      port: <%= ENV['PRODUCTION_DB_READ_REPLICA_2_PORT'] || 5432 %>
      weight: 30
    - host: <%= ENV['PRODUCTION_DB_READ_REPLICA_3'] %>
      port: <%= ENV['PRODUCTION_DB_READ_REPLICA_3_PORT'] || 5432 %>
      weight: 20
  
  # Backup configuration
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 30
    s3_bucket: <%= ENV['BACKUP_S3_BUCKET'] %>
    encryption: true
  
  # Monitoring and alerting
  monitoring:
    enable_metrics: true
    slow_query_threshold: 1000
    connection_pool_monitoring: true
    error_reporting: true
    
    # Alert thresholds
    alerts:
      connection_pool_exhaustion: 90
      slow_query_rate: 10
      error_rate: 5
      disk_usage: 85

# Environment-specific overrides
environments:
  docker:
    adapter: postgresql
    database: ecommerce
    username: postgres
    password: password
    host: db
    port: 5432
    pool: 10
    
  kubernetes:
    adapter: postgresql
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_SERVICE_HOST'] %>
    port: <%= ENV['DB_SERVICE_PORT'] %>
    ssl_mode: require
    
    # Kubernetes-specific settings
    readiness_probe:
      enabled: true
      initial_delay: 30
      period: 10
      timeout: 5
      failure_threshold: 3
    
    liveness_probe:
      enabled: true
      initial_delay: 60
      period: 30
      timeout: 10
      failure_threshold: 3

# Migration settings
migrations:
  auto_migrate: false
  migration_timeout: 300
  backup_before_migration: true
  
  # Migration strategies
  strategies:
    development: immediate
    test: immediate
    staging: blue_green
    production: rolling_update
  
  # Rollback configuration
  rollback:
    enabled: true
    automatic_on_failure: false
    backup_retention: 7

# Connection pooling configuration
connection_pool:
  # Pool sizing
  min_size: 5
  max_size: 50
  acquire_timeout: 30
  idle_timeout: 600
  max_lifetime: 3600
  
  # Health checks
  health_check_interval: 30
  health_check_query: "SELECT 1"
  
  # Retry configuration
  retry_attempts: 3
  retry_backoff: exponential
  max_retry_delay: 10

# Query optimization
query_optimization:
  enable_prepared_statements: true
  statement_cache_size: 1000
  query_timeout: 30
  
  # Index hints
  use_index_hints: true
  force_index_usage: false
  
  # Query analysis
  explain_queries: false
  log_slow_queries: true
  slow_query_threshold: 1000

# Security configuration
security:
  # Encryption
  encryption_at_rest: true
  encryption_in_transit: true
  
  # Authentication
  require_authentication: true
  authentication_timeout: 300
  
  # Authorization
  row_level_security: true
  column_level_security: false
  
  # Audit logging
  audit_logging: true
  audit_log_retention: 90
  
  # Data masking
  enable_data_masking: true
  mask_sensitive_fields:
    - email
    - phone
    - address
    - payment_info

# Performance monitoring
performance:
  enable_monitoring: true
  metrics_collection_interval: 60
  
  # Metrics to collect
  metrics:
    - connection_count
    - active_queries
    - query_duration
    - cache_hit_ratio
    - lock_waits
    - deadlocks
    - disk_io
    - memory_usage
  
  # Performance thresholds
  thresholds:
    max_query_duration: 5000
    max_connection_time: 300
    max_lock_wait_time: 1000
    min_cache_hit_ratio: 0.95

# Disaster recovery
disaster_recovery:
  # Backup strategy
  backup_strategy: continuous
  backup_frequency: hourly
  full_backup_frequency: daily
  
  # Recovery options
  point_in_time_recovery: true
  cross_region_replication: true
  automated_failover: true
  
  # Recovery testing
  recovery_testing_schedule: monthly
  recovery_time_objective: 4h
  recovery_point_objective: 1h