[package]
name = "llmkg"
version = "0.1.0"
edition = "2021"
authors = ["LLMKG Team"]
description = "Lightning-fast knowledge graph optimized for LLM integration"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ahash = "0.8"
slotmap = { version = "1.0", features = ["serde"] }
bumpalo = "3.16"
bytemuck = "1.16"

# Compression and optimization
zstd = "0.13"
bloom = "0.3"
bincode = "1.3"
bit-vec = "0.6"

# Async runtime
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
regex = "1.10"
chrono = { version = "0.4", features = ["serde"] }

# UUID generation
uuid = { version = "1.10", features = ["v4", "serde"] }

# Random number generation
rand = "0.8"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
log = "0.4"
env_logger = "0.11"

# Concurrency
parking_lot = "0.12"
crossbeam = "0.8"
rayon = "1.8"

# System monitoring
sysinfo = "0.30"

# Web and monitoring dependencies
tokio-tungstenite = "0.20"
warp = "0.3"
futures-util = "0.3"
reqwest = { version = "0.11", features = ["json"] }

# Math and SIMD
num-traits = "0.2"
nalgebra = { version = "0.33", optional = true }

web-sys = { version = "0.3", features = ["console", "Performance", "WorkerGlobalScope"], optional = true }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }

# Additional dependencies needed by tests
sha2 = "0.10"
tower = "0.4"
num_cpus = "1.16"

# Test infrastructure dependencies (optional)
rusqlite = { version = "0.30", features = ["bundled"], optional = true }
axum = { version = "0.7", optional = true }
tower-http = { version = "0.5", features = ["cors", "fs"], optional = true }
handlebars = { version = "5.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.5"
tempfile = "3.12"
rusqlite = { version = "0.30", features = ["bundled"] }
axum = "0.7"
tower-http = { version = "0.5", features = ["cors", "fs"] }
handlebars = "5.0"
bincode = "1.3"
dotenv = "0.15"
mockall = "0.12"
test-case = "3.3"

[profile.release]
lto = true
opt-level = "s"
strip = true

[profile.release.package."*"]
opt-level = "s"

[features]
default = ["native"]
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "console_error_panic_hook", "wee_alloc", "js-sys", "web-sys", "getrandom"]
native = ["nalgebra"]
simd = []
cuda = []
mcp = []

[[test]]
name = "phase4_realistic_tests"
path = "tests/phase4_realistic_tests.rs"

[[test]]
name = "phase4_deepseek_integration"
path = "tests/phase4_deepseek_integration.rs"

[[test]]
name = "phase4_comprehensive_tests"
path = "tests/phase4_comprehensive_tests.rs"

[[test]]
name = "phase4_advanced_stress_tests"
path = "tests/phase4_advanced_stress_tests.rs"

[[test]]
name = "phase4_integration_scenarios"
path = "tests/phase4_integration_scenarios.rs"

[[test]]
name = "phase1_cognitive_algorithm_tests"
path = "tests/phase1_cognitive_algorithm_tests.rs"

[[test]]
name = "phase1_simple_cognitive_tests"
path = "tests/phase1_simple_cognitive_tests.rs"

[profile.test]
opt-level = 2  # Optimize tests for better performance

[profile.bench]
debug = true  # Include debug info in benchmarks

[[bench]]
name = "realistic_benchmarks"
harness = false
