# Test configuration for LLMKG
# This file helps manage test execution and prevent hanging

[test-settings]
# Maximum time per test in seconds
timeout = 30

# Number of test threads (1 prevents resource contention)
threads = 1

# Test groups for isolated execution
[test-groups]
# Core functionality tests (safe to run)
core = [
    "core::graph::",
    "core::types::",
    "core::entity::",
    "core::memory::",
]

# Brain-related tests (potential async issues)
brain = [
    "core::brain_enhanced_graph::",
    "core::activation_engine::",
    "core::knowledge_engine::",
]

# Async/streaming tests (known to have loops)
async = [
    "streaming::",
    "federation::",
    "monitoring::dashboard::",
]

# Learning and cognitive tests
learning = [
    "learning::",
    "cognitive::",
]

# Math and utility tests
utils = [
    "math::",
    "validation::",
    "mcp::",
]