[build]
# Optimize test builds  
target-dir = "target"

# Safe Windows linker configuration
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "link-arg=/DEBUG:FULL",     # Full debug info for troubleshooting
    "-C", "link-arg=/OPT:NOREF",      # Prevent aggressive optimizations
    "-C", "link-arg=/OPT:NOICF",      # Disable identical COMDAT folding 
]

# Configure test execution
[test]
# Reduce concurrency to prevent resource exhaustion  
jobs = 1
# Add timeout for individual tests
timeout = 60

# Environment variables for tests
[env]
RUST_TEST_THREADS = "1"
RUST_BACKTRACE = "1"
RUST_LOG = "warn"

[alias]
# Safe test command that ensures cleanup
test-safe = "test --test-threads=1 --nocapture"
test-release = "test --release --test-threads=1"