[target.'cfg(test)']
runner = "cargo"

[build]
# Optimize test builds
target-dir = "target"

# Configure test execution
[test]
# Reduce concurrency to prevent resource exhaustion  
jobs = 1
# Add timeout for individual tests
timeout = 30

# Environment variables for tests
[env]
RUST_TEST_THREADS = "1"
RUST_BACKTRACE = "1"