pub mod graph;
pub mod entity;
pub mod entity_compat;
pub mod interned_entity;
pub mod types;
pub mod brain_types;
pub mod activation_config;
pub mod activation_processors;
pub mod activation_engine;
pub mod sdr_core;
pub mod sdr_index;
pub mod sdr_types;
pub mod sdr_storage;
pub mod brain_enhanced_graph;
pub mod memory;
pub mod triple;
pub mod knowledge_types;
pub mod knowledge_embedding;
pub mod knowledge_extraction;
pub mod knowledge_engine;
pub mod semantic_summary;
pub mod parallel;
pub mod zero_copy_types;
pub mod zero_copy_engine;
pub use zero_copy_types::BenchmarkResult;
pub mod phase1_types;
pub mod phase1_helpers;
pub mod phase1_integration;
pub mod entity_extractor;
// pub mod ai_entity_extractor;
pub mod relationship_extractor;
pub mod question_parser;
pub mod answer_generator;
pub mod cognitive_question_answering;

pub use phase1_integration::Phase1IntegrationLayer;
pub use phase1_types::{Phase1Config, QueryResult, CognitiveQueryResult, Phase1Statistics};