pub mod types;
pub mod orchestrator;
pub mod convergent;
pub mod convergent_enhanced;
pub mod divergent;
pub mod lateral;
pub mod systems;
pub mod critical;
pub mod abstract_pattern;
pub mod adaptive;
pub mod neural_query;
pub mod neural_bridge_finder;
pub mod pattern_detector;
pub mod tuned_parameters;
pub mod working_memory;
pub mod attention_manager;
pub mod attention_manager_traits;
pub mod inhibitory;
pub mod inhibitory_logic;
pub mod memory_integration;
pub mod phase3_integration;
pub mod phase4_integration;
pub mod graph_query_engine;

pub use types::*;
pub use crate::core::brain_types::{ActivationStep, ActivationOperation};
pub use crate::core::types::{GraphQuery, TraversalParams};
pub use orchestrator::{CognitiveOrchestrator, CognitiveOrchestratorConfig, OrchestratorStatistics};
pub use convergent::ConvergentThinking;
pub use convergent_enhanced::EnhancedConvergentThinking;
pub use divergent::DivergentThinking;
pub use lateral::LateralThinking;
pub use systems::SystemsThinking;
pub use critical::CriticalThinking;
pub use abstract_pattern::AbstractThinking;
pub use adaptive::AdaptiveThinking;
pub use neural_query::{NeuralQueryProcessor, QueryUnderstanding, QueryIntent};
pub use working_memory::{WorkingMemorySystem, MemoryQuery, MemoryRetrievalResult, MemoryContent, BufferType, MemoryItem};
pub use attention_manager::{AttentionManager, AttentionState, AttentionFocus, AttentionType, AttentionTarget, AttentionTargetType, ExecutiveCommand};
pub use inhibitory::{CompetitiveInhibitionSystem, InhibitionResult, CompetitionGroup, CompetitionType, InhibitionPerformanceMetrics};
pub use memory_integration::{UnifiedMemorySystem, MemoryIntegrationResult, RetrievalStrategy, MemoryType, ConsolidationResult, UnifiedRetrievalResult};
pub use phase3_integration::{Phase3IntegratedCognitiveSystem, Phase3QueryResult, SystemDiagnostics};
pub use phase4_integration::{Phase4CognitiveSystem, Phase4QueryResult, Phase4LearningResult};
pub use graph_query_engine::{GraphQueryEngine, GraphTraversalParams, GraphStructureAnalysis, GraphSynthesis};